name: Deploy Node.js app

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Puedes especificar la versión de Node.js que necesites

    - name: Create .env file
      run: |
        touch .env
        echo "HELLO=${{ secrets.HELLO }}" >> .env

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start