name: Deploy Node.js app

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Ajusta según la versión de Node.js que necesites

    - name: Parse JSON secret and create .env file
      run: |
        echo "Creating .env file..."
        # Extraer las variables desde el JSON secreto
        echo "${{ fromJson(secrets.DB_CONFIG).DB_USER }}" > .env
        echo "DB_USER=${{ fromJson(secrets.DB_CONFIG).DB_USER }}" >> .env
        echo "DB_PASS=${{ fromJson(secrets.DB_CONFIG).DB_PASS }}" >> .env
        echo "DB_HOST=${{ fromJson(secrets.DB_CONFIG).DB_HOST }}" >> .env
        echo "DB_NAME=${{ fromJson(secrets.DB_CONFIG).DB_NAME }}" >> .env

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start
      env:
        NODE_ENV: production  # Otras variables necesarias para tu aplicación
